import 'package:flutter/material.dart';
import '../services/api_service.dart';
import '../services/auth_service.dart';
import 'home_screen.dart';

class RegisterScreen extends StatefulWidget { const RegisterScreen({super.key}); @override State<RegisterScreen> createState()=>_RegisterScreenState(); }
class _RegisterScreenState extends State<RegisterScreen>{
 final _form=GlobalKey<FormState>(); final _name=TextEditingController(),_email=TextEditingController(),_password=TextEditingController(),_age=TextEditingController(text:'70');
 String _role='elderly',_language='English'; bool _busy=false,_obscure=true;
 final langs=const ['English','Hindi','Assamese','Bengali','Manipuri','Khasi','Mizo','Naga'];
 @override void dispose(){_name.dispose();_email.dispose();_password.dispose();_age.dispose();super.dispose();}
 Future<void> _submit() async{if(!_form.currentState!.validate())return;setState(()=>_busy=true);try{final r=await ApiService.register(name:_name.text.trim(),email:_email.text.trim(),password:_password.text,role:_role,age:int.parse(_age.text),language:_language);await AuthService.saveLogin(token:r['access_token'].toString(),userId:r['user_id'].toString(),role:r['role'].toString());if(!mounted)return;Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>HomeScreen(userId:r['user_id'].toString(),role:r['role'].toString(),token:r['access_token'].toString())),(_)=>false);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>_busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Create Account')),body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:560),child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Form(key:_form,child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('Join Cognitive Care',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:24),TextFormField(controller:_name,decoration:const InputDecoration(labelText:'Full name',border:OutlineInputBorder()),validator:(v)=>v==null||v.trim().isEmpty?'Enter your name':null),const SizedBox(height:14),TextFormField(controller:_email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Email',border:OutlineInputBorder()),validator:(v)=>v==null||!v.contains('@')?'Enter a valid email':null),const SizedBox(height:14),TextFormField(controller:_password,obscureText:_obscure,decoration:InputDecoration(labelText:'Password',border:const OutlineInputBorder(),suffixIcon:IconButton(onPressed:()=>setState(()=>_obscure=!_obscure),icon:Icon(_obscure?Icons.visibility:Icons.visibility_off))),validator:(v)=>v==null||v.length<8?'Use at least 8 characters':null),const SizedBox(height:14),DropdownButtonFormField<String>(initialValue:_role,decoration:const InputDecoration(labelText:'Account type',border:OutlineInputBorder()),items:const [DropdownMenuItem(value:'elderly',child:Text('Elderly / Patient')),DropdownMenuItem(value:'caregiver',child:Text('Caregiver'))],onChanged:(v)=>setState(()=>_role=v??'elderly')),const SizedBox(height:14),TextFormField(controller:_age,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Age',border:OutlineInputBorder()),validator:(v){final n=int.tryParse(v??'');return n==null||n<18||n>120?'Enter an age from 18 to 120':null;}),const SizedBox(height:14),DropdownButtonFormField<String>(initialValue:_language,decoration:const InputDecoration(labelText:'Preferred language',border:OutlineInputBorder()),items:langs.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>_language=v??'English')),const SizedBox(height:24),SizedBox(height:56,child:ElevatedButton(onPressed:_busy?null:_submit,child:Text(_busy?'CREATING...':'CREATE ACCOUNT',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))))]))))));
}
